name: Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "The version to release starting with `v`"
        required: true
        type: string

      release_ref:
        description: "The branch, tag or SHA to checkout (default to latest)"
        default: ""
        type: string

permissions:
  contents: write

jobs:
  publish-package:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install packages
        run: yarn install --frozen-lockfile

      - run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: publish-package

    name: Create release
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Create tag
        run: |
          git fetch --tags --no-recurse-submodules
          if [ ! $(git tag -l ${{ inputs.release_tag }}) ]; then
            git tag ${{ inputs.release_tag }}
            git push origin ${{ inputs.release_tag }}
          fi

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.release_tag }}
          name: ${{ inputs.release_tag }}
          draft: false

  build-assets:
    needs: create-release

    name: Add assets
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact-name: disk.rbxm
            path: build/disk.rbxm
            asset-type: application/octet-stream

          - artifact-name: disk-bundled.lua
            path: build/disk.lua
            asset-type: text/plain

    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build assets
        run: yarn run build-assets

      - name: Upload asset
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.path }}

      - name: Add asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ matrix.path }}
          asset_name: ${{ matrix.artifact-name }}
          asset_content_type: ${{ matrix.asset-type }}
